version: '3.5'

services: 
  postgres:
    container_name: answer_postgres_container
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: answer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5438:5432"

